Microverse-portfolio-mobile-version
SolomonTheCoder/Microverse-portfolio-mobile-version pull request #1
Opened 2023-02-20 08:23 UTC by SolomonTheCoder

This is my Microverse-portfolio-mobile-version project.
In this project, I
. Added an HTML file.
. Added a CSS file.

2023-02-20 10:09 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @SolomonTheCoder 👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Required Changes ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 10:09 UTC, TuyishimireEric commented on index.html
> +          <ul class="list">
- [ ] Kindly as suggested in the project requirements, I think it would be better to lay out the elements in the ```Works``` section using **CSS Grid** and **Flexbox** combined (it is mandatory that you use both). Kindly, Use **CSS Grid** in the main container that contains all of the cards and use **Flexbox** to lay out an individual card. 😎😎

You may follow this[ link ](https://css-tricks.com/snippets/css/complete-guide-grid/)for more info on CSS grid 🙏

2023-02-20 10:09 UTC, TuyishimireEric commented on index.html
> +      </div>
- [ ] I think it would be better to add the proper background image by using ```CSS background-image``` Kindly it is recommended that decorations are backgrounded images, not ```img``` tags 🙏

2023-02-20 10:09 UTC, TuyishimireEric commented on index.html
> +          <ul class="list">
- [ ] I have noticed that you are using a fixed **width of 372px and other fixed width** 😎😎
 Kindly, using **fixed width** in mobile-first responsive web design can cause scaling problems across different screen sizes. Fixed width can lead to horizontal scrolling and content that doesn't fit or scale correctly. To avoid these issues, it's recommended to use relative units like **percentages or ems** to make the design more flexible and adaptable.

Please follow this[ link on CSS units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) and try to resize the width of your content to fit mobile devices with 100% width 👍 

![image](https://user-images.githubusercontent.com/102757126/220062997-32ac6bfe-6146-474a-bcac-bfacb0d0ec70.png)

2023-02-20 10:09 UTC, TuyishimireEric commented on README.md
> +  <summary>Server</summary>
- [ ] **Good job on using the [Microverse README template](https://github.com/microverseinc/readme-template)** However, It would be better to replace the default information with the Repo details to make it professional 👍

2023-02-20 10:09 UTC, TuyishimireEric commented on index.html
> +    </div>
- [ ] I have noticed that you didn't add all the elements to the About section  as given on the Figma template design 😨, Kindly it would be better to add and replicate the given design 

**Figma design** | **Your design**
| --- | --- |
![image](https://user-images.githubusercontent.com/102757126/220072930-eb0f3f17-4a8f-4b4c-b7ef-e5596cbf3171.png) | ![image](https://user-images.githubusercontent.com/102757126/220073673-a276da66-8d79-4337-96ab-d85867624104.png)



**Note:** _using all the given components from a Figma design can improve the quality and consistency of the design, ._

2023-02-20 10:09 UTC, TuyishimireEric commented on index.html
> +      <p>
- [ ] Kindly, I would suggest using a ```section``` for the about section, for the better semantic to replace  ```<div class="About">``` 🙏 
- [ ]  You may also use another ```hx``` tag instead of using the ```<h1>``` as it marks the webpage's main title, so it would be better to have only 1 ```<h1>``` tag on a page 🙏

2023-02-21 10:27 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @SolomonTheCoder, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 16:03 UTC, franclobo reviewed
Hi @SolomonTheCoder, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project,  that is using one PR for two different milestones. You have approved the `Portfolio: finish mobile version` and you have submitted the `Portfolio: add a contact form and finish the mobile version` activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-04 16:46 UTC, merged